authorName: admin
experimentName: lr_kf
maxExecDuration: 20m
maxTrialNum: 10
searchSpacePath: search_space.json
trainingServicePlatform: local
trial: {codeDir: ., command: python3
    Kf_LogisticRegression.py, gpuNum: 0}
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
  classArgs: {optimize_mode: maximize}
useAnnotation: false
